window.es={};es.exportSymbol=function(a,c){for(var b=a.split("."),d=window,e=0;e<b.length-1;e++)d=d[b[e]];d[b[b.length-1]]=c};var config=window.esConfig||{},extend=function(a,c){var b;if(a&&c){for(b in c)a[b]=c[b];return a}},config=extend(config,{namespace:"es.objects"});(function(){for(var a=config.namespace.split("."),c=window,b=0;b<a.length;b++)void 0===c[a[b]]&&(c[a[b]]={}),c=c[a[b]];es.generatedNamespace=c})();es.getGeneratedNamespaceObj=function(){return es.generatedNamespace};
es.exportSymbol("es",es);es.RowState={INVALID:0,UNCHANGED:2,ADDED:4,DELETED:8,MODIFIED:16};es.exportSymbol("es.RowState",es.RowState);es.getType=function(a){return es.getGeneratedNamespaceObj()[a]};es.clearTypes=function(){es.generatedNamespace={}};es.onError=ko.observable({});es.onError.subscribe(function(a){throw JSON.stringify(a);});es.isArray=function(a){return!a?!1:a.isArray||"[object Array]"===Object.prototype.toString.call(a)};
es.objectKeys=Object.keys||function(a){var c=[],b;for(b in a)c.push(b);return c};es.isEsCollection=function(a){var c=!1;es.isArray(a)&&0<a.length&&a[0].hasOwnProperty("RowState")&&(c=!0);return c};es.exportSymbol("es.isEsCollection",es.isEsCollection);
var utils={copyDataIntoEntity:function(a,c){var b;if(a&&c){for(b in a)if(c.hasOwnProperty(b))if(ko.isObservable(a[b]))a[b](c[b]);else a[b]=c[b];return a}},extend:function(a,c){var b;if(a&&c){for(b in c)a[b]=c[b];return a}},addPropertyChangedHandlers:function(a,c){var b=a[c];ko.isObservable(b)&&!(b instanceof Array)&&b.subscribe(function(){!1===a.ignorePropertyChanged&&-1===ko.utils.arrayIndexOf(a.ModifiedColumns(),c)&&"RowState"!==c&&(a.ModifiedColumns.push(c),a.RowState()!==es.RowState.MODIFIED&&
a.RowState()!==es.RowState.ADDED&&a.RowState(es.RowState.MODIFIED))})},startTracking:function(a){var c;if(a.hasOwnProperty("RowState")){if(!ko.isObservable(a.RowState))a.RowState=ko.observable(a.RowState)}else a.RowState=ko.observable(es.RowState.ADDED);a.hasOwnProperty("ModifiedColumns");a.ModifiedColumns=ko.observableArray();for(c in a)if("RowState"!==c&&"ModifiedColumns"!==c&&"__type"!==c&&"esExtendedData"!==c){var b=a[c];b instanceof Array||a.hasOwnProperty(c)&&ko.isObservable(b)&&utils.addPropertyChangedHandlers(a,
c)}return a},expandExtraColumns:function(a,c){var b,d,e=c||!1;if(a.esExtendedData&&es.isArray(a.esExtendedData)){b=ko.isObservable(a.esExtendedData)?a.esExtendedData():a.esExtendedData;for(d=0;d<b.length;d++)a[b[d].Key]=e?ko.observable(b[d].Value):b[d].Value;delete a.esExtendedData}if(void 0!==b){a.esExtendedData=[];for(d=0;d<b.length;d++)a.esExtendedData.push(ko.isObservable(b[d].Key)?b[d].Key():b[d].Key)}return a},removeExtraColumns:function(a){var c,b;if(a.esExtendedData&&es.isArray(a.esExtendedData)){b=
ko.isObservable(a.esExtendedData)?a.esExtendedData():a.esExtendedData;for(c=0;c<b.length;c++)delete a[b[c]];delete a.esExtendedData}return a},shallowCopy:function(a){if("object"===typeof a&&null!==a){var c;if(es.isArray(a))c=[];else if(a instanceof Date)c=new Date(a);else if(a instanceof Boolean)c=new Boolean(a);else if(a instanceof Number)c=new Number(a);else if(a instanceof String)c=new String(a);else if(Object.create&&Object.getPrototypeOf)c=Object.create(Object.getPrototypeOf(a));else if(a.__proto__||
a.constructor.prototype){var b=a.__proto__||a.constructor.prototype||{},d=function(){};d.prototype=b;c=new d;if(!c.__proto__)c.__proto__=b}ko.utils.arrayForEach(es.objectKeys(a),function(b){if(!es.isEsCollection(a[b]))switch(b){case "___esEntity___":case "esTypeDefs":case "routes":case "ignorePropertyChanged":break;default:c[b]=a[b]}});return c}return a},getDirtyGraph:function(a){var c,b,d,e=[],h=null;es.Visit(a).forEach(function(a){if("esExtendedData"===this.key)this.block();else if(!1===this.isLeaf){if(a instanceof
Array)return a;if(a.hasOwnProperty("RowState"))switch(a.RowState){case es.RowState.ADDED:case es.RowState.DELETED:case es.RowState.MODIFIED:e.push(this.path)}}return a});if(0<e.length){h=d=es.isArray(a)?[]:utils.shallowCopy(utils.removeExtraColumns(a));for(c=0;c<e.length;c++){var g=e[c],i=a;d=h;for(b=0;b<g.length;b++)d.hasOwnProperty(g[b])?d=d[g[b]]:es.isArray(i[g[b]])&&(d[g[b]]=[],d=d[g[b]]),i=i[g[b]];i=utils.removeExtraColumns(i);es.isArray(d)?d.push(utils.shallowCopy(i)):d=utils.shallowCopy(i)}}return h}};
utils.newId=function(){var a=(new Date).getTime();return function(){return++a}}();es.utils=utils;es.exportSymbol("es.extend",es.extend);es.exportSymbol("es.startTracking",es.startTracking);es.exportSymbol("es.getDirtyGraph",es.getDirtyGraph);es.Visit=function(a){if(!(this instanceof es.Visit))return new es.Visit(a);this.value=a};es.Visit.prototype.forEach=function(a){return this.value=walk(this.value,a,!1)};
var walk=function(a,c,b){var d=[],e=[],h=!0,g=function(a,b){if(a.forEach)return a.forEach(b);for(var c=0;c<a.length;c++)b(a[c],c,a)};return function l(a){var j=b?copy(a):a,m,n,o,p,k=!0,f={node:j,node_:a,path:[].concat(d),parent:e[e.length-1],parents:e,key:d.slice(-1)[0],isRoot:0===d.length,level:d.length,circular:null,update:function(a,b){f.isRoot||(f.parent.node[f.key]=a);f.node=a;b&&(k=!1)},"delete":function(a){delete f.parent.node[f.key];a&&(k=!1)},remove:function(a){es.isArray(f.parent.node)?
f.parent.node.splice(f.key,1):delete f.parent.node[f.key];a&&(k=!1)},keys:null,before:function(a){m=a},after:function(a){n=a},pre:function(a){o=a},post:function(a){p=a},stop:function(){h=!1},block:function(){k=!1}};if(!h)return f;if("object"===typeof j&&null!==j){f.keys=es.objectKeys(j);f.isLeaf=0===f.keys.length;for(j=0;j<e.length;j++)if(e[j].node_===a){f.circular=e[j];break}}else f.isLeaf=!0;f.notLeaf=!f.isLeaf;f.notRoot=!f.isRoot;a=c.call(f,f.node);void 0!==a&&f.update&&f.update(a);m&&m.call(f,
f.node);if(!k)return f;"object"===typeof f.node&&null!==f.node&&!f.circular&&(e.push(f),g(f.keys,function(a,c){d.push(a);o&&o.call(f,f.node[a],a);var e=l(f.node[a]);if(b&&Object.hasOwnProperty.call(f.node,a))f.node[a]=e.node;e.isLast=c==f.keys.length-1;e.isFirst=0==c;p&&p.call(f,e);d.pop()}),e.pop());n&&n.call(f,f.node);return f}(a).node};
es.EsEntity=function(){var a,c=[];this.ignorePropertyChanged=!1;this.routes={};this.customize=function(a){c.push(a);return this};this.init=function(){a=this;a.___esEntity___=es.utils.newId();ko.utils.arrayForEach(c,function(b){b&&b.call(a)});es.utils.startTracking(a)};this.populateEntity=function(b){var c,e,h;a.ignorePropertyChanged=!0;try{for(c in es.utils.copyDataIntoEntity(a,b),es.utils.expandExtraColumns(a,!0),b)b.hasOwnProperty(c)&&this.esTypeDefs&&this.esTypeDefs[c]&&((e=es.getType(this.esTypeDefs[c]))?
(h=new e,h.hasOwnProperty("___esCollection___")?h.populateCollection(b[c]):h.populateEntity(b[c]),this[c]=h):es.isArray(b[c])?(this[c]=b[c],ko.utils.arrayForEach(this[c],function(){})):this[c]=b[c])}finally{a.ignorePropertyChanged=!1}};this.applyDefaults=function(){};this.markAsDeleted=function(){this.hasOwnProperty("RowState")?this.RowState()!==es.RowState.DELETED&&this.RowState(es.RowState.DELETED):this.RowState=ko.observable(es.RowState.DELETED);this.hasOwnProperty("ModifiedColumns")&&this.ModifiedColumns.removeAll()};
this.load=function(b){a=this;b.async=void 0!==b.success||void 0!==b.error?!0:!1;if(b.route)b.url=b.route.url||this.routes[b.route].url,b.type=b.route.method||this.routes[b.route].method;var c=b.success,e=b.error;b.success=function(b,e){a.populateEntity(b);c&&c.call(a,b,e.state)};b.error=function(b,c,d){e&&e.call(a,b,c,d.state)};es.dataProvider.execute(b)};this.loadByPrimaryKey=function(a,c,e,h){var g={route:this.routes.loadByPrimaryKey};1===arguments.length&&arguments[0]&&"object"===typeof arguments[0]?
es.utils.extend(g,arguments[0]):(g.data=a,g.success=c,g.error=e,g.state=h);this.load(g)};this.save=function(b,c,e){a=this;var h,g={success:b,error:c,state:e};1===arguments.length&&arguments[0]&&"object"===typeof arguments[0]&&es.utils.extend(g,arguments[0]);g.async=void 0!==g.success||void 0!==g.error?!0:!1;h=a.routes.commit;switch(a.RowState()){case es.RowState.ADDED:h=a.routes.create||h;break;case es.RowState.MODIFIED:h=a.routes.update||h;break;case es.RowState.DELETED:h=a.routes.del||h}g.route=
h;g.data=es.utils.getDirtyGraph(ko.toJS(a));if(h)g.url=h.url,g.type=h.method;var i=g.success,l=g.error;g.success=function(b,c){a.populateEntity(b);i&&i.call(a,b,c.state)};g.error=function(b,c,e){l&&l.call(a,b,c,e.state)};es.dataProvider.execute(g)}};es.exportSymbol("es.EsEntity",es.EsEntity);es.exportSymbol("es.EsEntity.populateEntity",es.EsEntity.populateEntity);es.exportSymbol("es.EsEntity.markAsDeleted",es.EsEntity.markAsDeleted);es.exportSymbol("es.EsEntity.load",es.EsEntity.load);
es.exportSymbol("es.EsEntity.loadByPrimaryKey",es.EsEntity.loadByPrimaryKey);es.exportSymbol("es.EsEntity.save",es.EsEntity.save);es.EsEntityCollection=function(){var a=ko.observableArray([]);ko.utils.extend(a,es.EsEntityCollection.fn);a.___esCollection___=es.utils.newId();return a};
es.EsEntityCollection.fn={filter:function(a){var c=this();return ko.utils.arrayFilter(c,a)},markAllAsDeleted:function(){var a,c,b=this(),d=b.length;for(a=0;a<d;a+=1)c=b[a],c.markAsDeleted&&c.markAsDeleted()},populateCollection:function(a){var c=this.entityTypeName,b,d=[],e=this.createEntity,h;c&&(b=es.getType(c));a&&es.isArray(a)&&(ko.utils.arrayForEach(a,function(a){h=e(a,b);void 0!==h&&null!==h&&d.push(h)}),this(d))},createEntity:function(a,c){var b;b=c;if(!c)b=this.entityTypeName,b=es.getType(b);
b?(b=new b,b.populateEntity(a)):b=a;return b},load:function(a){var c=this;a.async=void 0!==a.success||void 0!==a.error?!0:!1;if(a.route)a.url=a.route.url||this.routes[a.route].url,a.type=a.route.method||this.routes[a.route].method;var b=a.success,d=a.error;a.success=function(a,d){c.populateCollection(a);b&&b.call(c,a,d.state)};a.error=function(a,b,g){d&&d.call(c,a,b,g.state)};es.dataProvider.execute(a)},loadAll:function(a,c,b){var d={route:this.routes.loadAll};1===arguments.length&&arguments[0]&&
"object"===typeof arguments[0]?es.utils.extend(d,arguments[0]):(d.success=a,d.error=c,d.state=b);this.load(d)},save:function(a,c,b){var d=this,e={success:a,error:c,state:b};1===arguments.length&&arguments[0]&&"object"===typeof arguments[0]&&es.utils.extend(e,arguments[0]);e.async=void 0!==e.success||void 0!==e.error?!0:!1;e.route=d.routes.commit;e.data=es.utils.getDirtyGraph(ko.toJS(d));if(e.route)e.url=e.route.url,e.type=e.route.method;var h=e.success,g=e.error;e.success=function(a){d.populateCollection(a);
h&&h.call(d,a,e.state)};e.error=function(a,b,c){g&&g.call(d,a,b,c.state)};es.dataProvider.execute(e)}};es.exportSymbol("es.EsEntityCollection",es.EsEntityCollection);es.exportSymbol("es.EsEntityCollection.markAllAsDeleted",es.EsEntityCollection.markAllAsDeleted);es.exportSymbol("es.EsEntityCollection.loadAll",es.EsEntityCollection.loadAll);es.exportSymbol("es.EsEntityCollection.load",es.EsEntityCollection.load);es.exportSymbol("es.EsEntityCollection.save",es.EsEntityCollection.save);
es.defineEntity=function(a,c){var b="string"!==typeof a,d=b?a:c,e=function(){d.call(this);this.applyDefaults();this.init()};e.prototype=new es.EsEntity;b||(es.generatedNamespace[a]=e);return e};es.exportSymbol("es.defineEntity",es.defineEntity);
es.defineCollection=function(a,c){var b="string"!==typeof a,d=b?a:c,e=function(){var a=new es.EsEntityCollection;a.entityTypeName=d;this.init.call(a);return a};e.prototype=new function(){var a=this,b=[];this.init=function(){var c=this;ko.utils.arrayForEach(b,function(a){a.call(c)});for(var d in a)a.hasOwnProperty(d)&&"init"!==d&&"customize"!==d&&(c[d]=a[d])};this.customize=function(a){b.push(a)}};b||(es.generatedNamespace[a]=e);return e};es.exportSymbol("es.defineCollection",es.defineCollection);
es.AjaxProvider=function(){var a=function(){},c=function(a,c){if("string"!==typeof c)return a.replace(/\{([^\}]+)\}/g,function(a,b){if(b in c)return ko.utils.unwrapObservable(c[b])})};this.execute=function(b){var d=b.success||a,e=b.error||a,b=$.extend({cache:!1,contentType:"application/json; charset=utf-8;",dataType:"json",type:"GET"},b);b.success=function(a){d(a,b)};b.error=function(a){if(e)e(a.status,a.responseText,b);else es.onError({code:a.status,message:a.responseText})};b.url=c(b.url,b.data);
if(b.data)b.data=ko.toJSON(b.data);$.ajax(b)}};es.dataProvider=new es.AjaxProvider;
