window.es={};es.exportSymbol=function(a,c){for(var b=a.split("."),e=window,d=0;d<b.length-1;d++)e=e[b[d]];e[b[b.length-1]]=c};var config=window.esConfig||{},extend=function(a,c){var b;if(a&&c){for(b in c)a[b]=c[b];return a}},config=extend(config,{namespace:"es.objects"});(function(){for(var a=config.namespace.split("."),c=window,b=0;b<a.length;b++)void 0===c[a[b]]&&(c[a[b]]={}),c=c[a[b]];es.generatedNamespace=c})();es.getGeneratedNamespaceObj=function(){return es.generatedNamespace};
es.exportSymbol("es",es);es.RowState={INVALID:0,UNCHANGED:2,ADDED:4,DELETED:8,MODIFIED:16};es.exportSymbol("es.RowState",es.RowState);es.DateParser=function(){this.deserialize=function(a){"string"===typeof a&&0===a.indexOf("/Date(")&&(a=new Date(parseInt(a.substr(6))));return a};this.serialize=function(a){return"/Date("+Date.UTC(a.getFullYear(),a.getMonth(),a.getDate(),a.getHours(),a.getMinutes(),a.getSeconds(),0)+")/"}};es.getType=function(a){return es.getGeneratedNamespaceObj()[a]};
es.clearTypes=function(){es.generatedNamespace={}};es.onError=ko.observable({});es.onError.subscribe(function(a){throw JSON.stringify(a);});es.isArray=function(a){a=ko.utils.unwrapObservable(a);return!a?!1:a.isArray||"[object Array]"===Object.prototype.toString.call(a)};es.objectKeys=Object.keys||function(a){var c=[],b;for(b in a)c.push(b);return c};
es.isEsCollection=function(a){var c=!1;void 0!==a&&void 0!==a.es&&void 0!==a.es.___esCollection___?c=!0:es.isArray(a)&&0<a.length&&a[0].hasOwnProperty("RowState")&&(c=!0);return c};es.isEsEntity=function(a){var c=!1;void 0!==a&&void 0!==a.es&&void 0!==a.es.___esEntity___&&(c=!0);return c};
es.lazyLoader=function(a,c){return function(){var b=void 0;if(0===arguments.length){if(void 0===b){b=this.createObjectFromType(c);if(void 0===b)throw"Please include the JavaScript class file for the '"+c+"'";b.load({route:a,data:this.esPrimaryKeys()})}return b()}}};es.exportSymbol("es.isEsCollection",es.isEsCollection);
var utils={dateParser:new es.DateParser,copyDataIntoEntity:function(a,c){var b,e;if(a&&c){for(b in a)if(c.hasOwnProperty(b))if(e=c[b],"string"===typeof e&&(e=utils.dateParser.deserialize(e)),ko.isObservable(a[b]))a[b](e);else a[b]=e;return a}},extend:function(a,c){var b;if(a&&c){for(b in c)a[b]=c[b];return a}},addPropertyChangedHandlers:function(a,c){var b=a[c];ko.isObservable(b)&&!(b instanceof Array)&&b.__ko_proto__!==ko.dependentObservable&&b.subscribe(function(b){var d;!1===a.es.ignorePropertyChanged&&
(d=a.esColumnMap[c],1===d&&(d=c),d=d||c,-1===ko.utils.arrayIndexOf(a.ModifiedColumns(),d)&&(a.es.originalValues[c]||(a.es.originalValues[c]=b),"RowState"!==c&&(a.ModifiedColumns.push(d),a.RowState()!==es.RowState.MODIFIED&&a.RowState()!==es.RowState.ADDED&&a.RowState(es.RowState.MODIFIED))))},a,"beforeChange")},startTracking:function(a){var c;if(a.hasOwnProperty("RowState")){if(!ko.isObservable(a.RowState))a.RowState=ko.observable(a.RowState)}else a.RowState=ko.observable(es.RowState.ADDED);a.hasOwnProperty("ModifiedColumns")?
a.ModifiedColumns([]):a.ModifiedColumns=ko.observableArray();for(c in a)if("ModifiedColumns"!==c&&"__type"!==c&&"esExtendedData"!==c&&"es"!==c){var b=a[c];b instanceof Array||a.hasOwnProperty(c)&&ko.isObservable(b)&&utils.addPropertyChangedHandlers(a,c)}return a},expandExtraColumns:function(a,c){var b,e,d=c||!1;if(a.esExtendedData&&es.isArray(a.esExtendedData)){b=ko.isObservable(a.esExtendedData)?a.esExtendedData():a.esExtendedData;for(e=0;e<b.length;e++)if(ko.isObservable(a[b[e].Key]))a[b[e].Key](b[e].Value);
else a[b[e].Key]=d?ko.observable(b[e].Value):b[e].Value;delete a.esExtendedData}return a},getDirtyGraph:function(a,c,b){var e,d,f,g;if(void 0===c&&!a.isDirtyGraph())return null;if(es.isEsEntity(a))for(e in es.isArray(b)?(d=a.prepareForJSON(),b.push(d),b=d):b=a.prepareForJSON(),void 0===c&&(c=b),a.esTypeDefs){if(void 0!==a[e]&&a[e].isDirtyGraph()){f=a[e].prepareForJSON();b[e]=[];for(g=0;g<f.length;g++)d=f[g],es.utils.getDirtyGraph(d,c,b[e])}}else{c=[];f=a.prepareForJSON();for(g=0;g<f.length;g++)d=
f[g],es.utils.getDirtyGraph(d,c,c)}return c}};utils.newId=function(){var a=(new Date).getTime();return function(){return++a}}();es.utils=utils;es.exportSymbol("es.extend",es.extend);es.exportSymbol("es.startTracking",es.startTracking);es.exportSymbol("es.getDirtyGraph",es.getDirtyGraph);
es.EsEntity=function(){var a=[];this.customize=function(c){a.push(c);return this};this.init=function(){var c=this;c.es.___esEntity___=es.utils.newId();c.es.ignorePropertyChanged=!1;c.es.originalValues={};c.es.isLoading=ko.observable(!1);es.utils.startTracking(c);ko.utils.arrayForEach(a,function(a){a&&a.call(c)});this.isDirty=ko.computed(function(){return c.RowState()!==es.RowState.UNCHANGED});this.isDirtyGraph=function(){var a=!1;if(c.RowState()!==es.RowState.UNCHANGED)return!0;for(propertyName in this.esTypeDefs)if(void 0!==
this[propertyName]&&(a=this[propertyName].isDirtyGraph(),!0==a))break;return a}};this.createObjectFromEsTypeDef=function(a){var b=void 0;this.esTypeDefs&&this.esTypeDefs[a]&&(EntityCtor=es.getType(this.esTypeDefs[a]))&&(b=new EntityCtor);return b};this.createObjectFromType=function(a){var b=void 0;(EntityCtor=es.getType(a))&&(b=new EntityCtor);return b};this.prepareForJSON=function(){var a=this,b={};ko.utils.arrayForEach(es.objectKeys(this),function(e){var d;switch(e){case "es":case "esRoutes":case "esTypeDefs":case "esRoutes":case "esColumnMap":case "esExtendedData":break;
case "RowState":b.RowState=ko.utils.unwrapObservable(a.RowState);break;case "ModifiedColumns":b.ModifiedColumns=ko.utils.unwrapObservable(a.ModifiedColumns);break;default:if(void 0!==a.esColumnMap[e]&&(d=ko.utils.unwrapObservable(a[e]),null===d||!es.isEsCollection(d)&&"function"!==typeof d&&void 0!==d))b[e]=null!=d&&d instanceof Date?utils.dateParser.serialize(d):d}});return b};this.populateEntity=function(a){var b,e,d;this.es.ignorePropertyChanged=!0;try{for(b in this.hasOwnProperty("ModifiedColumns")?
this.ModifiedColumns([]):this.ModifiedColumns=ko.observableArray(),this.es.originalValues={},es.utils.copyDataIntoEntity(this,a),es.utils.expandExtraColumns(this,!0),a)a.hasOwnProperty(b)&&this.esTypeDefs&&this.esTypeDefs[b]&&((e=es.getType(this.esTypeDefs[b]))?(d=new e,d.es.hasOwnProperty("___esCollection___")?d.populateCollection(a[b]):d.populateEntity(a[b]),this[b]=d):es.isArray(a[b])?(this[b]=a[b],ko.utils.arrayForEach(this[b],function(){})):this[b]=a[b])}finally{this.es.ignorePropertyChanged=
!1}};this.applyDefaults=function(){};this.acceptChanges=function(){this.es.originalValues={};this.ModifiedColumns([]);this.es.ignorePropertyChanged=!0;this.RowState(es.RowState.UNCHANGED);this.es.ignorePropertyChanged=!1};this.rejectChanges=function(){var a;if(this.es.originalValues){this.es.ignorePropertyChanged=!0;for(a in this.es.originalValues)this[a](this.es.originalValues[a]);this.ModifiedColumns([]);this.es.originalValues={};this.es.ignorePropertyChanged=!1}};this.markAsDeleted=function(){this.hasOwnProperty("RowState")?
this.RowState()!==es.RowState.DELETED&&this.RowState(es.RowState.DELETED):this.RowState=ko.observable(es.RowState.DELETED);this.hasOwnProperty("ModifiedColumns")&&this.ModifiedColumns.removeAll()};this.load=function(a){var b=this;b.es.isLoading(!0);a.async=void 0!==a.success||void 0!==a.error?!0:!1;if(a.route)a.url=a.route.url||this.esRoutes[a.route].url,a.type=a.route.method||this.esRoutes[a.route].method;var e=a.success,d=a.error;a.success=function(a,c){b.populateEntity(a);e&&e.call(b,a,c.state);
b.es.isLoading(!1)};a.error=function(a,c,e){d&&d.call(b,a,c,e.state);b.es.isLoading(!1)};es.dataProvider.execute(a);!1===a.async&&b.es.isLoading(!1)};this.loadByPrimaryKey=function(a,b,e,d){var f={route:this.esRoutes.loadByPrimaryKey};1===arguments.length&&arguments[0]&&"object"===typeof arguments[0]?es.utils.extend(f,arguments[0]):(f.data=a,f.success=b,f.error=e,f.state=d);this.load(f)};this.save=function(a,b,e){var d=this;d.es.isLoading(!0);var f={success:a,error:b,state:e,route:d.esRoutes.commit};
switch(d.RowState()){case es.RowState.ADDED:f.route=d.esRoutes.create||f.route;break;case es.RowState.MODIFIED:f.route=d.esRoutes.update||f.route;break;case es.RowState.DELETED:f.route=d.esRoutes["delete"]||f.route}1===arguments.length&&arguments[0]&&"object"===typeof arguments[0]&&es.utils.extend(f,arguments[0]);f.async=void 0!==f.success||void 0!==f.error?!0:!1;f.data=es.utils.getDirtyGraph(d);if(null===f.data){if(!1===f.async){d.es.isLoading(!1);return}f.success(null,f)}if(f.route)f.url=f.route.url,
f.type=f.route.method;var g=f.success,h=f.error;f.success=function(a,b){d.populateEntity(a);g&&g.call(d,a,b.state);d.es.isLoading(!1)};f.error=function(a,b,c){h&&h.call(d,a,b,c.state);d.es.isLoading(!1)};es.dataProvider.execute(f);!1===f.async&&d.es.isLoading(!1)}};es.exportSymbol("es.EsEntity",es.EsEntity);es.exportSymbol("es.EsEntity.populateEntity",es.EsEntity.populateEntity);es.exportSymbol("es.EsEntity.markAsDeleted",es.EsEntity.markAsDeleted);es.exportSymbol("es.EsEntity.load",es.EsEntity.load);
es.exportSymbol("es.EsEntity.loadByPrimaryKey",es.EsEntity.loadByPrimaryKey);es.exportSymbol("es.EsEntity.save",es.EsEntity.save);es.EsEntityCollection=function(){var a=ko.observableArray([]);a.es={};ko.utils.extend(a,es.EsEntityCollection.fn);a.es.___esCollection___=es.utils.newId();a.es.deletedEntities=new ko.observableArray;a.es.deletedEntities([]);a.es.isLoading=ko.observable(!1);return a};
es.EsEntityCollection.fn={filter:function(a){var c=this();return ko.utils.arrayFilter(c,a)},prepareForJSON:function(){var a=[];ko.utils.arrayForEach(this(),function(c){c.isDirtyGraph()&&a.push(c)});ko.utils.arrayForEach(this.es.deletedEntities(),function(c){c.RowState()!==es.RowState.ADDED&&a.push(c)});return a},acceptChanges:function(){ko.utils.arrayForEach(this(),function(a){a.RowState()!==es.RowState.UNCHANGED&&a.acceptChanges()});this.es.deletedEntities([])},rejectChanges:function(){var a=[],
c=0,b=0,e;ko.utils.arrayForEach(this.es.deletedEntities(),function(d){d.RowState()===es.RowState.ADDED?(a[c]=b,c+=1):d.rejectChanges();b+=1});if(0<a.length)for(b=a.length-1;0<=b;b--)this.es.deletedEntities.splice(a[b],1);a=[];ko.utils.arrayForEach(this(),function(b){switch(b.RowState()){case es.RowState.MODIFIED:b.rejectChanges();break;case es.RowState.ADDED:a.push(b)}});if(0<a.length)for(e=0;e<a.length;e++)b=ko.utils.arrayIndexOf(this(),a[e]),0<=b&&this.splice(b,1);0<this.es.deletedEntities().length&&
(e=this().concat(this.es.deletedEntities()),this(e));this.es.deletedEntities([])},markAllAsDeleted:function(){var a,c,b,e;this.es.deletedEntities(this.splice(0,this().length));b=this.es.deletedEntities;e=b().length;for(a=0;a<e;a+=1)if(c=b()[a],c.RowState()===es.RowState.UNCHANGED)c.hasOwnProperty("RowState")?c.RowState()!==es.RowState.DELETED&&c.RowState(es.RowState.DELETED):c.RowState=ko.observable(es.RowState.DELETED),c.hasOwnProperty("ModifiedColumns")&&c.ModifiedColumns.removeAll()},markAsDeleted:function(a){var c,
b,e,d;b=[];if(!arguments)throw Error("The entitiesOrEntityToDelete cannot be null or undefined.");if(es.isArray(a)){if(b=ko.utils.unwrapObservable(a),0===b.length)throw Error("The array passed in to markAsDeleted.markAsDeleted() cannot be empty.");}else for(c=0;c<arguments.length;c++)if(es.isEsEntity(arguments[c]))b.push(arguments[c]);else throw Error("Invalid type passed in to markAsDeleted.markAsDeleted()");this.es.deletedEntities(this.es.deletedEntities().concat(b));this.removeAll(b);e=this.es.deletedEntities;
d=e().length;for(c=0;c<d;c+=1)if(b=e()[c],b.RowState()===es.RowState.UNCHANGED)b.hasOwnProperty("RowState")?b.RowState()!==es.RowState.DELETED&&b.RowState(es.RowState.DELETED):b.RowState=ko.observable(es.RowState.DELETED),b.hasOwnProperty("ModifiedColumns")&&b.ModifiedColumns.removeAll()},populateCollection:function(a){var c=this.es.entityTypeName,b,e=[],d=this.createEntity,f;c&&(b=es.getType(c));a&&es.isArray(a)&&(ko.utils.arrayForEach(a,function(a){f=d(a,b);void 0!==f&&null!==f&&e.push(f)}),this(e))},
createEntity:function(a,c){var b;b=c;if(!c)b=this.es.entityTypeName,b=es.getType(b);b?(b=new b,b.populateEntity(a)):b=a;return b},addNew:function(){var a=null,c=this.es.entityTypeName;c&&(a=es.getType(c),a=new a,this.push(a));return a},load:function(a){var c=this;c.es.isLoading(!0);a.async=void 0!==a.success||void 0!==a.error?!0:!1;if(a.route)a.url=a.route.url||this.esRoutes[a.route].url,a.type=a.route.method||this.esRoutes[a.route].method;var b=a.success,e=a.error;a.success=function(a,e){c.populateCollection(a);
b&&b.call(c,a,e.state);c.es.isLoading(!1)};a.error=function(a,b,g){e&&e.call(c,a,b,g.state);c.es.isLoading(!1)};es.dataProvider.execute(a);!1===a.async&&c.es.isLoading(!1)},loadAll:function(a,c,b){var e={route:this.esRoutes.loadAll};1===arguments.length&&arguments[0]&&"object"===typeof arguments[0]?es.utils.extend(e,arguments[0]):(e.success=a,e.error=c,e.state=b);this.load(e)},save:function(a,c,b){var e=this;e.es.isLoading(!0);var d={success:a,error:c,state:b,route:e.esRoutes.commit};1===arguments.length&&
arguments[0]&&"object"===typeof arguments[0]&&es.utils.extend(d,arguments[0]);d.async=void 0!==d.success||void 0!==d.error?!0:!1;d.data=es.utils.getDirtyGraph(e);if(null===d.data){if(!1===d.async){e.es.isLoading(!1);return}d.success(null,d)}if(d.route)d.url=d.route.url,d.type=d.route.method;var f=d.success,g=d.error;d.success=function(a,b){e.es.deletedEntities([]);e.populateCollection(a);f&&f.call(e,a,b.state);e.es.isLoading(!1)};d.error=function(a,b,c){g&&g.call(e,a,b,c.state);e.es.isLoading(!1)};
es.dataProvider.execute(d);!1===d.async&&e.es.isLoading(!1)}};es.exportSymbol("es.EsEntityCollection",es.EsEntityCollection);es.exportSymbol("es.EsEntityCollection.markAllAsDeleted",es.EsEntityCollection.markAllAsDeleted);es.exportSymbol("es.EsEntityCollection.loadAll",es.EsEntityCollection.loadAll);es.exportSymbol("es.EsEntityCollection.load",es.EsEntityCollection.load);es.exportSymbol("es.EsEntityCollection.save",es.EsEntityCollection.save);
es.defineEntity=function(a,c){var b="string"!==typeof a,e=b?a:c,d=function(a){this.es={};e.call(this);this.applyDefaults();this.init();a&&this.populateEntity(a)};d.prototype=new es.EsEntity;b||(es.generatedNamespace[a]=d);return d};es.exportSymbol("es.defineEntity",es.defineEntity);
es.defineCollection=function(a,c){var b="string"!==typeof a,e=b?a:c,d=function(){var a=new es.EsEntityCollection;a.es.entityTypeName=e;this.init.call(a);return a};d.prototype=new function(){var a=this,b=[];this.init=function(){var c=this;ko.utils.arrayForEach(b,function(a){a.call(c)});for(var d in a)a.hasOwnProperty(d)&&"init"!==d&&"customize"!==d&&(c[d]=a[d]);this.isDirty=function(){var a,b,d=c(),e=!1;if(0<this.es.deletedEntities().length)e=!0;else if(0<d.length&&d[d.length-1].isDirty())e=!0;else for(a=
0;a<d.length;a++)if(b=d[a],b.RowState()!==es.RowState.UNCHANGED){e=!0;break}return e};this.isDirtyGraph=function(){var a,b,d=c();b=!1;if(0<this.es.deletedEntities().length)b=!0;else if(0<d.length&&d[d.length-1].isDirty())b=!0;else for(a=0;a<d.length;a++)if(b=d[a],b.RowState()!==es.RowState.UNCHANGED){b=!0;break}else if(b=b.isDirtyGraph(),!0===b)break;return b}};this.customize=function(a){b.push(a)}};b||(es.generatedNamespace[a]=d);return d};es.exportSymbol("es.defineCollection",es.defineCollection);
es.AjaxProvider=function(){var a=function(){},c=function(a,c){if("string"!==typeof c)return a.replace(/\{([^\}]+)\}/g,function(a,b){if(b in c)return ko.utils.unwrapObservable(c[b])})};this.execute=function(b){var e=b.success||a,d=b.error||a,b=$.extend({cache:!1,contentType:"application/json; charset=utf-8;",dataType:"json",type:"GET"},b);b.success=function(a){e(a,b)};b.error=function(a){if(d)d(a.status,a.responseText,b);else es.onError({code:a.status,message:a.responseText})};b.url=c(b.url,b.data);
if(b.data)b.data=ko.toJSON(b.data);$.ajax(b)}};es.dataProvider=new es.AjaxProvider;
