window.es={};es.exportSymbol=function(a,c){for(var b=a.split("."),d=window,f=0;f<b.length-1;f++)d=d[b[f]];d[b[b.length-1]]=c};var config=window.esConfig||{},extend=function(a,c){var b;if(a&&c){for(b in c)a[b]=c[b];return a}},config=extend(config,{namespace:"es.objects"});(function(){for(var a=config.namespace.split("."),c=window,b=0;b<a.length;b++)void 0===c[a[b]]&&(c[a[b]]={}),c=c[a[b]];es.generatedNamespace=c})();es.getGeneratedNamespaceObj=function(){return es.generatedNamespace};
es.exportSymbol("es",es);es.RowState={INVALID:0,UNCHANGED:2,ADDED:4,DELETED:8,MODIFIED:16};es.exportSymbol("es.RowState",es.RowState);es.getType=function(a){return es.getGeneratedNamespaceObj()[a]};es.clearTypes=function(){es.generatedNamespace={}};es.onError=ko.observable({});es.onError.subscribe(function(a){throw JSON.stringify(a);});es.isArray=function(a){return!a?!1:a.isArray||"[object Array]"===Object.prototype.toString.call(a)};
es.objectKeys=Object.keys||function(a){var c=[],b;for(b in a)c.push(b);return c};es.isEsCollection=function(a){var c=!1;es.isArray(a)&&0<a.length&&a[0].hasOwnProperty("RowState")&&(c=!0);return c};es.exportSymbol("es.isEsCollection",es.isEsCollection);
var utils={parseJSONDate:function(a){return new Date(parseInt(a.substr(6)))},copyDataIntoEntity:function(a,c){var b,d;if(a&&c){for(b in a)if(c.hasOwnProperty(b))if(d=c[b],ko.isObservable(a[b]))a[b](d);else a[b]=d;return a}},extend:function(a,c){var b;if(a&&c){for(b in c)a[b]=c[b];return a}},addPropertyChangedHandlers:function(a,c){var b=a[c];ko.isObservable(b)&&!(b instanceof Array)&&b.__ko_proto__!==ko.dependentObservable&&b.subscribe(function(b){!1===a.ignorePropertyChanged&&-1===ko.utils.arrayIndexOf(a.ModifiedColumns(),
c)&&(a.__OriginalValues[c]||(a.__OriginalValues[c]=b),"RowState"!==c&&(a.ModifiedColumns.push(c),a.RowState()!==es.RowState.MODIFIED&&a.RowState()!==es.RowState.ADDED&&a.RowState(es.RowState.MODIFIED)))},a,"beforeChange")},startTracking:function(a){var c;if(a.hasOwnProperty("RowState")){if(!ko.isObservable(a.RowState))a.RowState=ko.observable(a.RowState)}else a.RowState=ko.observable(es.RowState.ADDED);a.hasOwnProperty("ModifiedColumns");a.ModifiedColumns=ko.observableArray();a.__OriginalValues={};
for(c in a)if("RowState"!==c&&"ModifiedColumns"!==c&&"__type"!==c&&"esExtendedData"!==c){var b=a[c];b instanceof Array||a.hasOwnProperty(c)&&ko.isObservable(b)&&utils.addPropertyChangedHandlers(a,c)}return a},expandExtraColumns:function(a,c){var b,d,f=c||!1;if(a.esExtendedData&&es.isArray(a.esExtendedData)){b=ko.isObservable(a.esExtendedData)?a.esExtendedData():a.esExtendedData;for(d=0;d<b.length;d++)a[b[d].Key]=f?ko.observable(b[d].Value):b[d].Value;delete a.esExtendedData}if(void 0!==b){a.esExtendedData=
[];for(d=0;d<b.length;d++)a.esExtendedData.push(ko.isObservable(b[d].Key)?b[d].Key():b[d].Key)}return a},removeExtraColumns:function(a){var c,b;if(a.esExtendedData&&es.isArray(a.esExtendedData)){b=ko.isObservable(a.esExtendedData)?a.esExtendedData():a.esExtendedData;for(c=0;c<b.length;c++)delete a[b[c]];delete a.esExtendedData}return a},shallowCopy:function(a){if("object"===typeof a&&null!==a){var c;if(es.isArray(a))c=[];else if(a instanceof Date)c=new Date(a);else if(a instanceof Boolean)c=new Boolean(a);
else if(a instanceof Number)c=new Number(a);else if(a instanceof String)c=new String(a);else if(Object.create&&Object.getPrototypeOf)c=Object.create(Object.getPrototypeOf(a));else if(a.__proto__||a.constructor.prototype){var b=a.__proto__||a.constructor.prototype||{},d=function(){};d.prototype=b;c=new d;if(!c.__proto__)c.__proto__=b}ko.utils.arrayForEach(es.objectKeys(a),function(b){if(!es.isEsCollection(a[b]))switch(b){case "___esEntity___":case "esTypeDefs":case "routes":case "ignorePropertyChanged":break;
default:c[b]=a[b]}});return c}return a},getDirtyGraph:function(a){var c,b,d,f=[],e=null;es.Visit(a).forEach(function(a){if("esExtendedData"===this.key)this.block();else if(!1===this.isLeaf){if(a instanceof Array)return a;if(a.hasOwnProperty("RowState"))switch(a.RowState){case es.RowState.ADDED:case es.RowState.DELETED:case es.RowState.MODIFIED:f.push(this.path)}}return a});if(0<f.length){e=d=es.isArray(a)?[]:utils.shallowCopy(utils.removeExtraColumns(a));for(c=0;c<f.length;c++){var g=f[c],j=a;d=e;
for(b=0;b<g.length;b++)d.hasOwnProperty(g[b])?d=d[g[b]]:es.isArray(j[g[b]])&&(d[g[b]]=[],d=d[g[b]]),j=j[g[b]];j=utils.removeExtraColumns(j);es.isArray(d)?d.push(utils.shallowCopy(j)):d=utils.shallowCopy(j)}}return e}};utils.newId=function(){var a=(new Date).getTime();return function(){return++a}}();es.utils=utils;es.exportSymbol("es.extend",es.extend);es.exportSymbol("es.startTracking",es.startTracking);es.exportSymbol("es.getDirtyGraph",es.getDirtyGraph);
es.Visit=function(a){if(!(this instanceof es.Visit))return new es.Visit(a);this.value=a};es.Visit.prototype.forEach=function(a){return this.value=walk(this.value,a,!1)};
var walk=function(a,c,b){var d=[],f=[],e=!0,g=function(a,b){if(a.forEach)return a.forEach(b);for(var d=0;d<a.length;d++)b(a[d],d,a)};return function k(a){var i=b?copy(a):a,l,m,p,q,o=!0,h={node:i,node_:a,path:[].concat(d),parent:f[f.length-1],parents:f,key:d.slice(-1)[0],isRoot:0===d.length,level:d.length,circular:null,update:function(a,b){h.isRoot||(h.parent.node[h.key]=a);h.node=a;b&&(o=!1)},"delete":function(a){delete h.parent.node[h.key];a&&(o=!1)},remove:function(a){es.isArray(h.parent.node)?
h.parent.node.splice(h.key,1):delete h.parent.node[h.key];a&&(o=!1)},keys:null,before:function(a){l=a},after:function(a){m=a},pre:function(a){p=a},post:function(a){q=a},stop:function(){e=!1},block:function(){o=!1}};if(!e)return h;if("object"===typeof i&&null!==i){h.keys=es.objectKeys(i);h.isLeaf=0===h.keys.length;for(i=0;i<f.length;i++)if(f[i].node_===a){h.circular=f[i];break}}else h.isLeaf=!0;h.notLeaf=!h.isLeaf;h.notRoot=!h.isRoot;a=c.call(h,h.node);void 0!==a&&h.update&&h.update(a);l&&l.call(h,
h.node);if(!o)return h;"object"===typeof h.node&&null!==h.node&&!h.circular&&(f.push(h),g(h.keys,function(a,c){d.push(a);p&&p.call(h,h.node[a],a);var e=k(h.node[a]);if(b&&Object.hasOwnProperty.call(h.node,a))h.node[a]=e.node;e.isLast=c==h.keys.length-1;e.isFirst=0==c;q&&q.call(h,e);d.pop()}),f.pop());m&&m.call(h,h.node);return h}(a).node};
es.EsEntity=function(){var a,c=[];this.ignorePropertyChanged=!1;this.routes={};this.customize=function(a){c.push(a);return this};this.init=function(){a=this;a.___esEntity___=es.utils.newId();es.utils.startTracking(a);ko.utils.arrayForEach(c,function(b){b&&b.call(a)})};this.populateEntity=function(b){var d,c,e;a.ignorePropertyChanged=!0;try{for(d in es.utils.copyDataIntoEntity(a,b),es.utils.expandExtraColumns(a,!0),b)b.hasOwnProperty(d)&&this.esTypeDefs&&this.esTypeDefs[d]&&((c=es.getType(this.esTypeDefs[d]))?
(e=new c,e.hasOwnProperty("___esCollection___")?e.populateCollection(b[d]):e.populateEntity(b[d]),this[d]=e):es.isArray(b[d])?(this[d]=b[d],ko.utils.arrayForEach(this[d],function(){})):this[d]=b[d])}finally{a.ignorePropertyChanged=!1}};this.applyDefaults=function(){};this.rejectChanges=function(){if(this.__OriginalValues){for(prop in this.__OriginalValues)this[prop](this.__OriginalValues[prop]);this.ModifiedColumns=ko.observableArray();this.__OriginalValues={}}};this.markAsDeleted=function(){this.hasOwnProperty("RowState")?
this.RowState()!==es.RowState.DELETED&&this.RowState(es.RowState.DELETED):this.RowState=ko.observable(es.RowState.DELETED);this.hasOwnProperty("ModifiedColumns")&&this.ModifiedColumns.removeAll()};this.load=function(b){a=this;b.async=void 0!==b.success||void 0!==b.error?!0:!1;if(b.route)b.url=b.route.url||this.routes[b.route].url,b.type=b.route.method||this.routes[b.route].method;var d=b.success,c=b.error;b.success=function(b,c){a.populateEntity(b);d&&d.call(a,b,c.state)};b.error=function(b,d,j){c&&
c.call(a,b,d,j.state)};es.dataProvider.execute(b)};this.loadByPrimaryKey=function(a,d,c,e){var g={route:this.routes.loadByPrimaryKey};1===arguments.length&&arguments[0]&&"object"===typeof arguments[0]?es.utils.extend(g,arguments[0]):(g.data=a,g.success=d,g.error=c,g.state=e);this.load(g)};this.save=function(b,d,c){a=this;var e,g={success:b,error:d,state:c};1===arguments.length&&arguments[0]&&"object"===typeof arguments[0]&&es.utils.extend(g,arguments[0]);g.async=void 0!==g.success||void 0!==g.error?
!0:!1;e=a.routes.commit;switch(a.RowState()){case es.RowState.ADDED:e=a.routes.create||e;break;case es.RowState.MODIFIED:e=a.routes.update||e;break;case es.RowState.DELETED:e=a.routes.del||e}g.route=e;g.data=es.utils.getDirtyGraph(ko.toJS(a));if(e)g.url=e.url,g.type=e.method;var j=g.success,k=g.error;g.success=function(b,d){a.populateEntity(b);j&&j.call(a,b,d.state)};g.error=function(b,d,c){k&&k.call(a,b,d,c.state)};es.dataProvider.execute(g)}};es.exportSymbol("es.EsEntity",es.EsEntity);
es.exportSymbol("es.EsEntity.populateEntity",es.EsEntity.populateEntity);es.exportSymbol("es.EsEntity.markAsDeleted",es.EsEntity.markAsDeleted);es.exportSymbol("es.EsEntity.load",es.EsEntity.load);es.exportSymbol("es.EsEntity.loadByPrimaryKey",es.EsEntity.loadByPrimaryKey);es.exportSymbol("es.EsEntity.save",es.EsEntity.save);es.EsEntityCollection=function(){var a=ko.observableArray([]);ko.utils.extend(a,es.EsEntityCollection.fn);a.___esCollection___=es.utils.newId();return a};
es.EsEntityCollection.fn={filter:function(a){var c=this();return ko.utils.arrayFilter(c,a)},markAllAsDeleted:function(){var a,c,b=this(),d=b.length;for(a=0;a<d;a+=1)c=b[a],c.markAsDeleted&&c.markAsDeleted()},populateCollection:function(a){var c=this.entityTypeName,b,d=[],f=this.createEntity,e;c&&(b=es.getType(c));a&&es.isArray(a)&&(ko.utils.arrayForEach(a,function(a){e=f(a,b);void 0!==e&&null!==e&&d.push(e)}),this(d))},createEntity:function(a,c){var b;b=c;if(!c)b=this.entityTypeName,b=es.getType(b);
b?(b=new b,b.populateEntity(a)):b=a;return b},load:function(a){var c=this;a.async=void 0!==a.success||void 0!==a.error?!0:!1;if(a.route)a.url=a.route.url||this.routes[a.route].url,a.type=a.route.method||this.routes[a.route].method;var b=a.success,d=a.error;a.success=function(a,d){c.populateCollection(a);b&&b.call(c,a,d.state)};a.error=function(a,b,g){d&&d.call(c,a,b,g.state)};es.dataProvider.execute(a)},loadAll:function(a,c,b){var d={route:this.routes.loadAll};1===arguments.length&&arguments[0]&&
"object"===typeof arguments[0]?es.utils.extend(d,arguments[0]):(d.success=a,d.error=c,d.state=b);this.load(d)},save:function(a,c,b){var d=this,f={success:a,error:c,state:b};1===arguments.length&&arguments[0]&&"object"===typeof arguments[0]&&es.utils.extend(f,arguments[0]);f.async=void 0!==f.success||void 0!==f.error?!0:!1;f.route=d.routes.commit;f.data=es.utils.getDirtyGraph(ko.toJS(d));if(f.route)f.url=f.route.url,f.type=f.route.method;var e=f.success,g=f.error;f.success=function(a,b){d.populateCollection(a);
e&&e.call(d,a,b.state)};f.error=function(a,b,c){g&&g.call(d,a,b,c.state)};es.dataProvider.execute(f)}};es.exportSymbol("es.EsEntityCollection",es.EsEntityCollection);es.exportSymbol("es.EsEntityCollection.markAllAsDeleted",es.EsEntityCollection.markAllAsDeleted);es.exportSymbol("es.EsEntityCollection.loadAll",es.EsEntityCollection.loadAll);es.exportSymbol("es.EsEntityCollection.load",es.EsEntityCollection.load);es.exportSymbol("es.EsEntityCollection.save",es.EsEntityCollection.save);
es.defineEntity=function(a,c){var b="string"!==typeof a,d=b?a:c,f=function(){d.call(this);this.applyDefaults();this.init()};f.prototype=new es.EsEntity;b||(es.generatedNamespace[a]=f);return f};es.exportSymbol("es.defineEntity",es.defineEntity);
es.defineCollection=function(a,c){var b="string"!==typeof a,d=b?a:c,f=function(){var a=new es.EsEntityCollection;a.entityTypeName=d;this.init.call(a);return a};f.prototype=new function(){var a=this,b=[];this.init=function(){var d=this;ko.utils.arrayForEach(b,function(a){a.call(d)});for(var c in a)a.hasOwnProperty(c)&&"init"!==c&&"customize"!==c&&(d[c]=a[c])};this.customize=function(a){b.push(a)}};b||(es.generatedNamespace[a]=f);return f};es.exportSymbol("es.defineCollection",es.defineCollection);
es.XMLHttpRequestProvider=function(){var a,c,b=function(){};this.baseURL="http://localhost";a=function(){var a;try{a=new XMLHttpRequest}catch(b){try{a=new ActiveXObject("Msxml2.XMLHTTP")}catch(c){try{a=new ActiveXObject("Microsoft.XMLHTTP")}catch(g){return alert("This sample only works in browsers with AJAX support"),!1}}}return a};c=function(a,b){var c=JSON.parse(a);if(void 0!==b.response)switch(b.response){case "entity":return c[b.response];case "collection":return c[b.response]}return c};this.execute=
function(d){var f=null,e,g,j;g=d.success||b;j=d.error||b;e=a();f=this.baseURL+d.url;e.open("POST",f,d.async||!1);e.setRequestHeader("Content-type","application/json; charset=utf-8");if(!0===d.async)e.onreadystatechange=function(){4===e.readyState&&(200===e.status?g(c(e.responseText,d.route),d):j(e.status,e.statusText,d))};e.send(ko.toJSON(d.data));!1===d.async&&(200===e.status?"{}"!==e.responseText&&""!==e.responseText&&g(c(e.responseText,d.route),d):j(e.status,e.responseText,d))};this.makeRequest=
function(c,f,e,g,j){var k=null,n=null,n=!1,i,l,m;if(void 0!==g||void 0!==j)n=!0,l=g||b,m=j||b;i=a();i.open("POST",c+f,n);i.setRequestHeader("Content-type","application/json; charset=utf-8");if(!0===n)i.onreadystatechange=function(){4===i.readyState&&(200===i.status?l(JSON.parse(i.responseText)):m(i.status,i.statusText))};i.send(e);if(!1===n)200===i.status?"{}"!==i.responseText&&""!==i.responseText&&(k=JSON.parse(i.responseText)):es.makeRequstError=i.statusText;return k}};es.dataProvider=new es.XMLHttpRequestProvider;
